[workspace]
members = [
  "crates/hypercore",
  "crates/hypercore-openai",
  "crates/hypercore-tools",
  "crates/hypercore-memory-sqlite",
  "crates/hypercore-examples",
  "crates/hypercore-symbolic",
  "crates/hypercore-hybrid",
  "crates/hypercore/runner",
]
resolver = "3"
