[package]
name = "hypercore-hybrid"
version = "0.1.0"
edition = "2024"

[dependencies]
hypercore-symbolic = { path = "../hypercore-symbolic" }
thiserror = "1.0"
tokio = { version = "1", features = ["rt", "macros"] }
